auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: DengYongBin
url: http://dengyongbin.github.io
feed: /atom.xml
author_info: <a href="http://dengyongbin.github.io/">DengYongBin</a>
